import type { NextPage } from 'next';
import Head from 'next/head';
import { Layout } from '../components/Layout';
import { useRouter } from 'next/router';
import { Button, Container, Stack, Typography } from '@mui/material';

const Home: NextPage = () => {
  const router = useRouter();
  
  return (
    <>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        {/* TODO */}
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Layout header footer>
        <Container>
          <Typography variant="h3" textAlign='center'>Welcome to Web3 renting platform</Typography>
          <Stack mt='2rem' gap={1} direction='row' justifyContent='space-evenly'>
            <Button size='large' variant='contained' onClick={() => router.push('/search?location=Prague')}>Find home</Button>
            <Button disabled size='large' variant='contained' onClick={() => router.push('/landlord')}>List apartment</Button>
          </Stack>
        </Container>
      </Layout>
    </>
  );
};

export default Home;
